- include_tasks: "{{ ansible_distribution }}/add_php_repository.yml"

- name: Install php along with modules
  package: name={{ item }} state=present
  with_items:
    - "php{{ php_version }}"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-cgi"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-zip"
    - "php{{ php_version }}-opcache"
    - "php{{ php_version }}-xsl"
    - "php{{ php_version }}-tidy"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-bcmath"

- name: Set the php configuration file
  template:
    src=templates/php.ini.j2
    dest="/etc/php/{{ php_version }}/fpm/php.ini"
  notify:
  - restart php service

- name: Set the PHP fpm configuraiton
  template:
    src=templates/php_fpm.conf.j2
    dest="/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
  notify:
    - restart php service
